"""initial models

Revision ID: e56e97139a68
Revises: None
Create Date: 2026-06-07 16:28:56.775932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56e97139a68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('parent_message_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_parent_message_id'), 'messages', ['parent_message_id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_index('ix_messages_session_parent', 'messages', ['session_id', 'parent_message_id'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_feedbacks',
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_user_feedbacks_rating'), 'user_feedbacks', ['rating'], unique=False)
    op.create_index(op.f('ix_user_feedbacks_trace_id'), 'user_feedbacks', ['trace_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('global_role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_global_role'), 'users', ['global_role'], unique=False)
    op.create_table('parent_documents',
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(length=4294967295), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('parent_id')
    )
    op.create_index(op.f('ix_parent_documents_team_id'), 'parent_documents', ['team_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    op.drop_index(op.f('ix_parent_documents_team_id'), table_name='parent_documents')
    op.drop_table('parent_documents')
    op.drop_index(op.f('ix_users_global_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_feedbacks_trace_id'), table_name='user_feedbacks')
    op.drop_index(op.f('ix_user_feedbacks_rating'), table_name='user_feedbacks')
    op.drop_table('user_feedbacks')
    op.drop_table('teams')
    op.drop_index('ix_messages_session_parent', table_name='messages')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_parent_message_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
