"""optimize indexes and cascades

Revision ID: e7babcbdd989
Revises: e56e97139a68
Create Date: 2026-06-07 16:32:03.520051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7babcbdd989'
down_revision: Union[str, None] = 'e56e97139a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.alter_column('parent_documents', 'content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=False)
    op.drop_constraint(op.f('parent_documents_ibfk_1'), 'parent_documents', type_='foreignkey')
    op.create_foreign_key(None, 'parent_documents', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_constraint(None, 'parent_documents', type_='foreignkey')
    op.create_foreign_key(op.f('parent_documents_ibfk_1'), 'parent_documents', 'teams', ['team_id'], ['team_id'])
    op.alter_column('parent_documents', 'content',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###
